import type { FlipBook } from "./sample-flipbook";

/**
 * Real novels generated by DraftToDone (public/sample/novels), exported from
 * their interior PDFs and cover images without retouching. Each was scanned
 * page by page for template brackets, blanks and orphan headings before being
 * chosen; the pages shown were read.
 */
const NOVELS = [
  { slug: "shipwreck", title: "The Secret of the Shipwreck", pages: 142, nums: { mid: 76, late: 131 } },
  { slug: "polwenna", title: "The Secrets of Polwenna Cove", pages: 138, nums: { mid: 72, late: 129 } },
  { slug: "ink-ice", title: "Ink, Ice, and Inquest", pages: 155, nums: { mid: 79, late: 147 } },
  { slug: "dead-men", title: "Dead Men Don’t Return Library Books", pages: 141, nums: { mid: 74, late: 132 } },
] as const;

type Captions = {
  cover: string;
  title: string;
  toc: string;
  ch1: string;
  ch1b: string;
  /** Token {n}: the page number in the printed book. */
  mid: string;
  late: string;
  kind: string;
  pages: string;
};

export function novelBooks(c: Captions): FlipBook[] {
  return NOVELS.map((b) => {
    const dir = `/sample/novels/${b.slug}`;
    const page = (file: string, caption: string) => ({
      src: `${dir}/${file}.webp`,
      caption,
      alt: `${b.title} — ${caption}`,
    });
    return {
      id: b.slug,
      title: b.title,
      meta: `${c.kind} · ${b.pages} ${c.pages}`,
      pageCount: b.pages,
      cover: `${dir}/cover.webp`,
      pages: [
        page("cover", c.cover),
        page("title", c.title),
        page("toc", c.toc),
        page("ch1", c.ch1),
        page("ch1b", c.ch1b),
        page("mid", c.mid.replace("{n}", String(b.nums.mid))),
        page("late", c.late.replace("{n}", String(b.nums.late))),
      ],
    };
  });
}

export const NOVEL_CAPTIONS: Record<"en" | "fr" | "it" | "de", Captions> = {
  en: { cover: "Front cover", title: "Title page", toc: "Table of contents", ch1: "Chapter 1", ch1b: "Chapter 1, continued", mid: "Mid-book, p. {n}", late: "Late in the book, p. {n}", kind: "Novel", pages: "pages" },
  fr: { cover: "Couverture", title: "Page de titre", toc: "Table des matières", ch1: "Chapitre 1", ch1b: "Chapitre 1, suite", mid: "Au milieu du livre, p. {n}", late: "Vers la fin, p. {n}", kind: "Roman", pages: "pages" },
  it: { cover: "Copertina", title: "Frontespizio", toc: "Indice", ch1: "Capitolo 1", ch1b: "Capitolo 1, seguito", mid: "A metà libro, p. {n}", late: "Verso la fine, p. {n}", kind: "Romanzo", pages: "pagine" },
  de: { cover: "Cover", title: "Titelseite", toc: "Inhaltsverzeichnis", ch1: "Kapitel 1", ch1b: "Kapitel 1, Fortsetzung", mid: "Buchmitte, S. {n}", late: "Gegen Ende, S. {n}", kind: "Roman", pages: "Seiten" },
};
